### ISSUE TITLE
Deauther 2.0: NodeMCU - timeout loading file run?... (on SCAN APS, SCAN STATIONS)

### ISSUE THREAD

**Issue by careyer** [spacehuhn/esp8266_deauther#762] opened 2018-03-30 09:33 UTC
Hi there,

The Scan AP and Scan Stations buttons do not work for me. After a while the following timeout message comes up and Deauther seems to have halted. I can't switch beteen the different pannels anymore (Scan, SSID, Attack...)

<img src="http://www.ip-networx.de/content/GitHub/Deuather2error.JPG">

BTW: On Firefox is seems to run an inital scan automatically (SSIDs and signal strenth are shown) whereas on IE and Chrome  the list of results stays empty.

**Comment by tobozo** [comment] 2018-03-30 09:42
You can get more debug info by using the serial connection.

If you can reproduce this, it would be helpful to copy/paste the serial output.

**Comment by careyer** [comment] 2018-03-30 10:12
Sure... willing to help! How can I open a serial connection? Putty? Via Wifi? Via COM? Bausrate?

**Comment by tobozo** [comment] 2018-03-30 10:19
Putty can do, but you may have to install a driver to see the ESP as a COM port 
Baudrate is 115200

**Comment by schinfo** [comment] 2018-03-30 10:28
It looks like there is a bug - in A_config.h (Line 48) setting "#define USE_DISPLAY false // will force display on" doesn't work - display is always on. I've the same problems and can reproduce it  - maybe it's a timing problem when the display is on. I've reported it to Spacehuhn - waiting for his answer.

**Comment by tobozo** [comment] 2018-03-30 10:32
@schinfo maybe create an issue for that ?

Also don't forget to power-cycle the ESP after changing the display settings, if you only reset the ESP, the display will "remember" its last settings and can stay on.

**Comment by tobozo** [comment] 2018-03-30 10:34
@careyer it seems like a normal behaviour, it can be annoying if you have more than one pre-recorded SSID+credentials, this is why the Serial interface comes more handy :-)

Please close this issue if it's solved.

**Comment by spacehuhn** [comment] 2018-03-30 11:42
Scan aps should work, if not paste in the serial output.
Scan stations will cause a hold the access point until the scan is finished - you will have to reconnect.

**Comment by tobozo** [comment] 2018-04-02 12:12
closing this as solved, feel free to reopen if applicable

**Closed by tobozo** 2018-04-02 12:12 UTC

**Comment by vitaliyivanov0802** [comment] 2020-06-28 15:00
> Привет,
> 
> Кнопки Scan AP и Scan Station не работают для меня. Через некоторое время появляется следующее сообщение таймаута, и Deauther, кажется, остановился. Я больше не могу переключать beteen на разные панели (сканирование, SSID, атака...)
> 
> ![](https://camo.githubusercontent.com/3ce8f72be1ec52f9d50a0eca1e51cdda67ece90a/687474703a2f2f7777772e69702d6e6574776f72782e64652f636f6e74656e742f4769744875622f4465756174686572326572726f722e4a5047)
> 
> BTW: на Firefox, кажется, запустить начальное сканирование автоматически (SSIDs и сигнал strenth показаны), в то время как на IE и Chrome список результатов остается пустым.

Как подключишь устройство к сети напряжения, включи на своем телефоне не вайфай, а точку доступа.
Как погаснет синяя лампочка - включаешь wi-fi, подключается к pwned, и вауаля, работает как новый.
