### ISSUE TITLE
Upload Problem

### ISSUE THREAD

**Issue by FloidHekmatyar** [spacehuhn/esp8266_deauther#765] opened 2018-03-30 19:07 UTC
Hello guys :) 

i tried too upload the Code but i get the following error message. 

```
In file included from C:\Users\Jonas\Desktop\Wifi\esp8266_deauther-master\esp8266_deauther\esp8266_deauther.ino:10:0:

sketch\functions.h:5:25: fatal error: ArduinoJson.h: No such file or directory

 #include "ArduinoJson.h"

                         ^

compilation terminated.

exit status 1
Fehler beim Kompilieren für das Board Generic ESP8266 Module.

```

**Comment by spacehuhn** [comment] 2018-03-30 19:59
Duplicate of https://github.com/spacehuhn/esp8266_deauther/issues/764 ?

**Comment by spacehuhn** [comment] 2018-04-04 21:04
Were you able to fix it?

**Comment by tobozo** [comment] 2018-04-09 17:48
Closing this issue for lack of followup, feel free to reopen if anything new comes up.

**Closed by tobozo** 2018-04-09 17:48 UTC
Labels: duplicate
