### ISSUE TITLE
Wrong Deauth Packet

### ISSUE THREAD

**Issue by mlg556** [spacehuhn/esp8266_deauther#795] opened 2018-04-08 20:38 UTC
This will sound weird, but when I select and attack my iPhone (with MAC 2c:f0:a2:98:37:35) connected to my network MLG74, (with BSSID f8:23:b2:71:a8:75); the deauth packets sent from the ESP module appear to be coming from another unrelated wrong AP, (with BSSID c0:25:e9:95:7b:00) even though my iPhone is not and can not be connected to that AP. It would seem that the program is "misreading" the access-point the client is connected to (maybe an index problem?). I have attached to image files explaining the problem. I have also emptied the module and re-uploaded the .ino file, which did not seem to fix it.

![issue1](https://user-images.githubusercontent.com/26349315/38472249-f44c2bb6-3b85-11e8-8110-3cb61156a84c.png)
![issue](https://user-images.githubusercontent.com/26349315/38472250-f469725c-3b85-11e8-84df-e91fabea6c80.png)

**Comment by spacehuhn** [comment] 2018-04-09 05:50
Thanks! I will try to reproduce the error and look into it.

**Comment by mlg556** [comment] 2018-04-09 10:25
Thanks for the reply! I have managed to identify the problem further. The `scan` correctly identifies the stations and their access points, but when I run an empty deauth attack`attack -d` (with nothing selected) and then prompt `show` to show the list one more time (without scanning again), the devices and their AP's are all wrong. It would seem that somehow the `attack -d` code messes up with the list. I have attached two images illustrating this. Also, it is important to note that when I `add`my device to the list with a name, select it with that name and attack; the attack successfully works.
![iss](https://user-images.githubusercontent.com/26349315/38493027-6b275e04-3bf9-11e8-925b-1dd6a064d0f0.png)
![iss1](https://user-images.githubusercontent.com/26349315/38493026-6b09a850-3bf9-11e8-9442-e820dda67633.png)

**Comment by spacehuhn** [comment] 2018-04-09 11:08
Yes the problem is when the AP-list gets sorted and the indices change. I'm currently restructuring the code to fix that.

**Comment by spacehuhn** [comment] 2018-04-09 12:29
Should be fixed now

**Comment by mlg556** [comment] 2018-04-09 12:45
Thx for the quick fix !

**Comment by tobozo** [comment] 2018-04-09 15:15
@mlg556 thanks for the quality of your feedback

**Comment by spacehuhn** [comment] 2018-04-09 19:17
Yeah thanks for the detailed infos! We're not seeing that very often here ;D

**Closed** 2018-04-11 17:42 UTC
Labels: Bug
