### ISSUE TITLE
Request Packet Monitor and Deauther Detector

### ISSUE THREAD

**Issue by ChandraOrbit** [spacehuhn/esp8266_deauther#750] opened 2018-03-27 05:25 UTC
1. Versi 2.0 no Packet Monitor on WEB GUI just on OLED
2. Request .. If possible the DeauthDetector can also be merged with ESP8266_Deauther.

thanks

**Comment by marek26340** [comment] 2018-03-27 06:16
1. that's normal
2. it's already done, you just need that OLED display.

**Comment by tobozo** [comment] 2018-03-27 06:58
Packet Monitor in the Web GUI: it's [easy to do with u8glib](https://github.com/tobozo/ghetto_blaster/blob/8951443766fd16c71006be466571921a15a67ac2/wificontrols.h#L63) and shouldn't be a problem to achieve with the current library.

The real underlying problem is the load on the ESP.  Adding too much polling to the webserver increases the probability it'll crash.

The only way I can think about to have screencap without impacting the stability would be to send the 1Kb along with every JSON response the server does, and let JavaScript draw something out of it.

**Comment by spacehuhn** [comment] 2018-03-27 07:47
The problem is that you can't have an access point open and host a web server while sniffing WiFi.
It's like with every other WiFi card. Either you use it as an access point to host a network, as a station to connect to one or you put it in the monitor mode to sniff for packets. But you can't have everything at the same time.

**Comment by tobozo** [comment] 2018-03-27 08:22
doh!

**Comment by spacehuhn** [comment] 2018-03-27 08:35
Using 2 ESPs could solve that ;)

**Comment by tobozo** [comment] 2018-03-27 09:19
yep, keeping the idea for when I'll manage to flash an ESP8266 from an ESP32 :-)

**Comment by ChandraOrbit** [comment] 2018-03-27 11:14
I agree if there are 2 ESPs in 1 board, so the esp8266_deauther software feature, packet monitoring and deauther detection can be explored, the container is concise and does not reduce user portability as well as convenience.

**Comment by lspoplove** [comment] 2018-03-27 11:19
After I upgrade all my products I can consider designing such board  with 2 ESPs


发自Naver邮箱应用软件
-----Original Message-----

**Comment by spacehuhn** [comment] 2018-03-28 07:43
The problem with 2 ESPs is, how would they communicate?
Via serial? That will make problems when trying to flash them! Unless there is some on/off switch for the serial lines.
Better would be a i2c or spi connection but I never programmed something like that, so no idea how much work that would be.

**Comment by tobozo** [comment] 2018-03-28 10:57
I have only tried serial so far, with partial success.

SPI version (untested yet): https://github.com/JiriBilek/WiFiSpiESP
Serial version (untested too):  https://github.com/jeelabs/esp-link

**Comment by spacehuhn** [comment] 2018-04-04 21:08
I'm going to close this because the main question got answered. 
It isn't possible to add the packet-monitor or deauth-detector to the web interface just like that. You'd need custom hardware and modified software, a lot of work for something that already works without problems using a $3 display from China.

**Closed by spacehuhn** 2018-04-04 21:08 UTC
Labels: enhancement
